### ISSUE TITLE
automatic polyfill header

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/CETL#16]
I'm only 90% sure this will work but we should provide a header like "cetl_polyfill.h" that uses C++20 feature testing (https://en.cppreference.com/w/cpp/feature_test) to include CETL types when they are absent from a given environment. This would support compilers that support the core C++20 language but which do not provide a full-featured standard library.

Not sure of the value of this so this should be a low priority task.

**Comment by pavel-kirienko** [comment]
there definitely is value in this
